version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
